# Generated by Django 3.2.13 on 2022-07-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='publish',
            new_name='date_of_brith',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='created',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='description',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='status',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
