# Generated by Django 3.2.13 on 2022-07-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220728_1039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='posts',
        ),
    ]
