# Generated by Django 3.2.13 on 2022-09-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_category_alter_category_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fav',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='fav',
            field=models.BooleanField(default=False),
        ),
    ]
