# Generated by Django 4.0.6 on 2022-07-28 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='read',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('publish', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('c', 'Compleat'), ('h', 'Have compleat')], max_length=1)),
            ],
        ),
    ]
